project:
  type: website
  output-dir: docs

website:
  title: "International Statistics Conference 2024<br>Case Study Poster Competition"
  site-url: "https://thiyangt.github.io/ISC2024.case.study/"
  navbar:
    right:
      - guidelines.qmd
      - registration.qmd
      - casestudy1.qmd
      - casestudy2.qmd
      - submissions.qmd
      - announcements.qmd

format:
  html:
    theme: materia
    css: styles.css
    toc: true

editor: visual

