---
title: "Competition Guidelines"
---

# 1. Participation and Team Formation Guidelines

1.1  The competition is open for undergraduates and recent graduates across all universities and Higher Education Institutes in Sri Lanka.

1.2  If the student is a recent graduate, the effective date of the degree should be after 01/01/2024.

1.3  The team must consist of 2 to 3 participants, with a minimum of 2 and a maximum of 3.

1.4 Team members may or may not be from the same university or higher education institution.

1.5 Teams can include only undergraduates, only recent graduates, or a mix of both.

# 2. Competition Task

2.1 There are two case studies available. Descriptions for Case Study 1 and Case Study 2 can be viewed by hovering over the respective tabs. 

2.2 Upon registration, datasets for both case studies will be provided.

2.3 Each team needs to select one case study and conduct analysis to achieve its listed objectives.

2.4 Based on their analysis, each team should submit the following documents: **1)  abstract, 2)  poster, 3) 10-minutes video presentation**

# 3. Important Dates

# 4. Abstract Guidelines

# 5. Poster Guidelines

# 6. 10-minutes Video Presentation Guidelines 


