---
title: "Competition Registration"
---

# Registration fee:

Per team: LKR 1000 only

# 1. Payment Methods:

## 1.1 Pay directly to the IASSL account

**Account details**

Account No: 003460001586

Account Name: Institute of Applied Statistics, Sri Lanka

Branch: Thimbirigasyaya

Bank: Sampath Bank

## 1.2 Pay via payment portal

Click [here](https://pay.iassl.lk/).

# 2. Declaration:

Fill [this](/declaration/declaration.pdf) declaration form.

# 3. Information and Documents Required to Complete the Registration Form:

-   Team Name
-   Names of Team Members
-   Email Addresses of Team Members
-   Contact Numbers of Team Members
-   Student ID (for undergraduates) or a Transcript/Verification Letter (for recent graduates) submitted as a single PDF file
-   Completed Declaration Form
-   Payment Receipt

# 4. Registration link:

<https://forms.gle/xT6YQxoVmL7V4MSz8>

# Upon registration, you will receive access to the data within 24 hours. If you do not receive access within this timeframe, please contact us at appstatsl\@gmail.com

NOTE: The Institute of Applied Statistics, Sri Lanka (IASSL) will provide access to a shared folder named **CaseStudyISC2024**. Inside this main folder, you will find two subfolders: **CaseStudy1** and **CaseStudy2**, each containing their respective data files and supporting documents.